framework:
    default_locale: en
    enabled_locales: ['en', 'fr', 'nl']
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks: ['fr', 'en', 'nl']
        providers:
